// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA63ZORAodp0lMe7vplwWSRgk9mbZ_Rt5c',
    appId: '1:431633313063:web:92a2fabb2beb98c7110d02',
    messagingSenderId: '431633313063',
    projectId: 'actually-happening-portal',
    authDomain: 'actually-happening-portal.firebaseapp.com',
    storageBucket: 'actually-happening-portal.appspot.com',
    measurementId: 'G-8016X6E64C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVOuao7oUgPlpxh--uCyaXjA4zgYy8N0w',
    appId: '1:431633313063:android:b986c7a2ece851b9110d02',
    messagingSenderId: '431633313063',
    projectId: 'actually-happening-portal',
    storageBucket: 'actually-happening-portal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcC7PJAkSGOSl9_chIMFoW6HeFef9Dmag',
    appId: '1:431633313063:ios:d8be0c1a2c1b0f32110d02',
    messagingSenderId: '431633313063',
    projectId: 'actually-happening-portal',
    storageBucket: 'actually-happening-portal.appspot.com',
    iosClientId: '431633313063-2tqg0kg8vu5eehrmts75i6u3nar3o8lb.apps.googleusercontent.com',
    iosBundleId: 'com.ahportal.first',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcC7PJAkSGOSl9_chIMFoW6HeFef9Dmag',
    appId: '1:431633313063:ios:d8be0c1a2c1b0f32110d02',
    messagingSenderId: '431633313063',
    projectId: 'actually-happening-portal',
    storageBucket: 'actually-happening-portal.appspot.com',
    iosClientId: '431633313063-2tqg0kg8vu5eehrmts75i6u3nar3o8lb.apps.googleusercontent.com',
    iosBundleId: 'com.ahportal.first',
  );
}
