# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push:
    branches : [master]

permissions:
  contents: read

jobs:
  test:
    # runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies for testing
      run: |
        cd python
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        pip install pytest
        pip install -e .
    
    - name: Run pytest tests
      env:
        ADAFRUIT_IO_USERNAME: ${{ secrets.ADAFRUIT_IO_USERNAME }}
        ADAFRUIT_IO_KEY: ${{ secrets.ADAFRUIT_IO_KEY }}
      run: python -m pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd python
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        pip install build twine
        pip install -e .

    - name: Build package
      run: |
        cd python
        python -m build

    - name: Publish package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: python -m twine upload --verbose -c CI --skip-existing python/dist/*